// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myorders;

#nullable disable

namespace application.Migrations.OrdersandPaymentDb
{
    [DbContext(typeof(OrdersandPaymentDbContext))]
    partial class OrdersandPaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("bookingdetails.MyCart", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderId"), 1L, 1);

                    b.Property<Guid?>("MyOrdersbookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("highlights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productPrice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("orderId");

                    b.HasIndex("MyOrdersbookingId");

                    b.ToTable("cartData");
                });

            modelBuilder.Entity("bookingdetails.MyOrders", b =>
                {
                    b.Property<Guid>("bookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cvv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deliveryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deliveryStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expireDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paidDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("paymentId")
                        .HasColumnType("int");

                    b.Property<int?>("shippingAddressaddressId")
                        .HasColumnType("int");

                    b.Property<string>("shippingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("totalAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("bookingId");

                    b.HasIndex("shippingAddressaddressId");

                    b.ToTable("orderDetails");
                });

            modelBuilder.Entity("users.UserDetail", b =>
                {
                    b.Property<int>("addressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("addressId"), 1L, 1);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("landmark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("zipcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("addressId");

                    b.ToTable("UserDetail");
                });

            modelBuilder.Entity("bookingdetails.MyCart", b =>
                {
                    b.HasOne("bookingdetails.MyOrders", null)
                        .WithMany("products")
                        .HasForeignKey("MyOrdersbookingId");
                });

            modelBuilder.Entity("bookingdetails.MyOrders", b =>
                {
                    b.HasOne("users.UserDetail", "shippingAddress")
                        .WithMany()
                        .HasForeignKey("shippingAddressaddressId");

                    b.Navigation("shippingAddress");
                });

            modelBuilder.Entity("bookingdetails.MyOrders", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
